stages:
  - build_api
  - deploy_fe

.run_deploy: &run_deploy
  stage: deploy_fe
  image: node:14-alpine
  script:
    - cd demo/
    - npm i --silent
    - PUBLIC_URL=${CI_ENVIRONMENT_URL}  API_URL=${API_URL} npm run build
    - npm i mime randomstring aws-sdk --silent
    - BUILD_DIRECTORY=dist BUCKET_NAME=$BUCKET_NAME AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} npm run deploy-aws
  tags:
    - wmfbooks-docker-runner

.run_build: &run_build
  stage: build_api
  script:
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:latest . 
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$APP_NAME:latest
  tags:
    - wmfbooks-shell-runner

.fe_env: &fe_env
  only:
    changes:
        - demo/*
  environment:
    name: wmfbooks-main
  variables:
    BUCKET_NAME: $S3_BUCKET
    API_URL: ${API_URL}

.be_env: &be_env
  only:
    - master
  environment:
    name: wmfbooks-main

deploy to fe:
  <<: *fe_env
  <<: *run_deploy

deploy to be:
  <<: *be_env
  <<: *run_build
