stages:
  - build_api
  - deploy_fe

.run_deploy: &run_deploy
  stage: deploy_fe
  image: node:14-alpine
  script:
    - cd demo/
    - npm i --silent
    - PUBLIC_URL=${CI_ENVIRONMENT_URL}  API_URL=${API_URL} npm run build
    - npm i mime randomstring aws-sdk --silent
    - BUILD_DIRECTORY=dist BUCKET_NAME=$BUCKET_NAME AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} npm run deploy-aws
  tags:
    - wmfbooks-docker-runner

.run_build: &run_build
  stage: build_api
  script:
    - apk add --update --no-cache build-base python3-dev python3 libffi-dev libressl-dev bash git gettext curl  
    - curl -O https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py && pip install --upgrade six awscli 
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPO
    - docker build -f Dockerfile -t $APP_NAME .
    - docker tag $APP_NAME:$DOCKER_REGISTRY/$APP_NAME:latest
    - docker tag $APP_NAME:$DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_TAG
    - docker push $DOCKER_REGISTRY/$APP_NAME:latest
    - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_TAG
    - aws ecs update-service --cluster $CLUSTER --service $SERVICE --force-new-deployment --region $REGION
  tags:
    - wmfbooks-docker-runner

.fe_env: &fe_env
  only:
    changes:
        - demo/*
  environment:
    name: wmfbooks-main
  variables:
    BUCKET_NAME: $S3_BUCKET
    API_URL: ${API_URL}

.be_env: &be_env
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: /var/run/docker.sock
  only:
    - master
  environment:
    name: wmfbooks-main

deploy to fe:
  <<: *fe_env
  <<: *run_deploy

deploy to be:
  <<: *be_env
  <<: *run_build
